services: 
  web:
      build: .
      environment:
        MYENV: EXAMPLE
      volumes:
        - data:/code
  web_migrate:
      extends:
        service: web
      command: python dragonnotes/manage.py migrate
  web_run:
      extends:
        service: web
      command: python dragonnotes/manage.py runserver 0.0.0.0:8000
      ports:
        - "5000:8000"
volumes:
  data:
    external: true