# Generated by Django 3.2.3 on 2021-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='path_to_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default='test.zip', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default="2021-05-17 4:00"),
            preserve_default=False,
        ),
    ]
