# Generated by Django 3.2.3 on 2021-05-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210517_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uploaded_at',
        ),
    ]
